Usermenu and yoid onboarding
didx-xyz/yoma pull request #621
Opened 2024-03-24 13:09 UTC by Matthew-Baird

- Nav User menu styling for desktop & mobile
- YoID Onboading Modal

2024-03-24 13:32 UTC, jasondicker requested changes

2024-03-24 13:32 UTC, jasondicker commented on src/web/src/components/Global.tsx
> +                EXITING UPDATE
Spelling mistake

2024-03-24 13:32 UTC, Matthew-Baird commented on src/web/src/components/Global.tsx
> +                EXITING UPDATE
Woopsies

2024-03-25 03:49 UTC, adrianwium approved these changes

2024-03-25 03:50 UTC, adrianwium approved these changes

2024-03-25 06:46 UTC, jasondicker approved these changes

2024-03-25 06:46 UTC, merged