Feature/register opportunity
didx-xyz/yoma pull request #73
Opened 2023-08-24 12:27 UTC by wdbasson

2023-08-24 12:32 UTC, rblaine95 requested changes

2023-08-24 12:32 UTC, rblaine95 commented on src/web/youth/.rtx.toml
This file isn't needed because there's a `.rtx.toml` in the root of the project

2023-08-24 12:39 UTC, rblaine95 requested changes

2023-08-24 12:45 UTC, wdbasson commented on src/web/youth/package.json
> +    "cypress": "^12.17.4",
Will remove for now...

2023-08-25 11:55 UTC, rblaine95 approved these changes
For what my review is worth, LGTM 👍

2023-08-28 12:50 UTC, rblaine95 commented
This is currently blocking #76 from progressing

2023-12-18 21:47 UTC, rblaine95 commented
@wdbasson @jasondicker can we close this PR?

2024-03-27 08:02 UTC, closed without merging